### ISSUE TITLE
Scratch Does not let This!

### ISSUE THREAD

**Issue by Torotv** [GreenBayRules/ScratchFollowersMessager#1]
**The Scratch Team note**

Hello There,. Sorry But We don't allow this!

They said this on my followermessenger 
That i created.

**Comment by Torotv** [comment]
https://www.remix3d.com/details/G009SXC52JH5?section=parts

**Comment by GreenBayRules** [comment]
Yeah I know.... I'm going to remove this. Thanks for this though, I totally forgot about it xD
